name: Run Sensor Simulation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-sensor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Sensor simulation
        run: timeout 10 python sensor.py || true
